sudo: required
dist: trusty

jobs:
  include:
    - stage: build docker image
    script:
    - docker build -t bitmex-docker:latest .
    - docker run --rm -v $(pwd):/ionicapp -it bitmex-docker:latest buildbrowser
# - sshpass -p $scpPass scp -r -o StrictHostKeyChecking=no ./platforms/browser/www/* root@pacecouriers.com:/usr/share/nginx/quantumex.ca/
