os:
- linux
sudo: true
addons:
  node_js:
    - "iojs"
    - "7"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - sshpass
    
before_install:
- ls -la
 - npm i -g npm@latest
before_script:
- git pull
- npm install -g ionic cordova

script:
- npm install 
- ionic cordova platform add browser
- ionic cordova build browser --prod
- sshpass -p $scpPass scp -r -o StrictHostKeyChecking=no ./platforms/browser/www/* root@pacecouriers.com:/usr/share/nginx/quantumex.ca/
- ls -la